import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import './globals.css';
import classnames from 'classnames';
import { IranSans } from '@/configs/font';

export const metadata: Metadata = {
  title: 'Hamrah Sell',
  description: 'Generated by Hamrah Aval',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={classnames(IranSans.className)}>
        <main>{children}</main>
        <Toaster richColors closeButton />
      </body>
    </html>
  );
}
