#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check EsLint Standards
npm run lint-check || {
    echo 'EsLint Check Failed'
    false
}

# Check tsconfig Standards
npm run type-check || {
    echo 'Type Check Failed'
    false
}

# Run Prettier
npm run format || {
    echo 'Prettier Check Failed'
    false
}

# Add Prettified files
git add .
