#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check EsLint Standards
pnpm lint-check || {
    echo 'EsLint Check Failed'
    false
}

# Check tsconfig Standards
pnpm type-check || {
    echo 'Type Check Failed'
    false
}

# Run Prettier
pnpm format || {
    echo 'Prettier Check Failed'
    false
}

# Add Prettified files
git add .
